# -*- coding: utf-8 -*-
"""fibonacci_both.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OD6yb_ksnU0I4mp2z2_IVuW9m0nv5Q1c

# Fibonacci series using recursion
"""

def fibonacci(val):
   if val <= 1:
      return val
   else:
      return(fibonacci(val-1) + fibonacci(val-2))
n = int(input("Enter no of terms in a series"))

if n <= 0:
   print("Enter a positive integer...")
else:
   print("The Fibonacci sequence is :")
   for i in range(n):
      print(fibonacci(i))

"""# Fibonacci series using non-recursion"""

max=int(input("Enter no of terms in a series"))
n1 = 0
n2 = 1

if(max==1):
  print(n1)
else: 
  print("The Fibonacci sequence is :")
  print(n1)
  print(n2) 
  for i in range(max-2):
    n3 = n1 + n2
    print(n3)
    n1 = n2
    n2 = n3

